# Generated by Django 4.2.3 on 2023-07-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='brand',
        ),
    ]
