# Generated by Django 4.2.3 on 2023-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_description_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='product-image'),
        ),
    ]
